// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Jun 28 10:51:37 2022

interfaceGeral interfaceGeral_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.id(id_sig) ,	// output [31:0] id_sig
	.outd1(outd1_sig) ,	// output [31:0] outd1_sig
	.outd2(outd2_sig) ,	// output [31:0] outd2_sig
	.outr1(outr1_sig) ,	// output [31:0] outr1_sig
	.pcout(pcout_sig) ,	// output [31:0] pcout_sig
	.outregw(outregw_sig) ,	// output [1:0] outregw_sig
	.outdm(outdm_sig) 	// output [31:0] outdm_sig
);

